name: iptv
description: "A Flutter IPTV application for Android TV"
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  http: ^1.5.0
  chewie: ^1.13.0
  video_player: ^2.10.0
  # 建议添加图片缓存库以提升性能
  # cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/background.jpg

flutter_icons:
  android: 'launcher_icon'
  ios: false
  image_path: "assets/icon/icon.png"